### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by valioDOTch** [jepp/jep-Slider-for-Sencha-Touch-1.1#2]
Which license applies to the code?
GPL? MIT?

**Comment by jepp** [comment]
As stated in the README:
"Since it incorporates a decent chunk of Sencha Touch code, the license is the same as it is for the rest of Sencha Touch."

**Comment by valioDOTch** [comment]
I haven't seen that.
So is it GPL3 & SenchaTouch Commercial license or just the first one? ;)

**Comment by jepp** [comment]
You can get Sencha Touch via multiple licenses. So it will be whatever license YOU use for Sencha Touch. Not sure how much clearer I can be.
